language: "en-US"
early_access: true
enable_free_tier: true

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  review_details: false
  auto_review:
    enabled: true
    drafts: false
  skip_paths:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/pnpm-lock.yaml"
  path_instructions:
    - path: "**/*.tsx"
      instructions: "Ensure that all TypeScript code follows the established coding standards and best practices"

chat:
  auto_reply: true