name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # App
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      UI_URL: ${{ vars.UI_URL }}
      # Database
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # JWT
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_EXPIRES_IN: ${{ vars.JWT_EXPIRES_IN }}
      # Mailing
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      # Google
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ vars.GOOGLE_REDIRECT_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Run lint
        run: pnpm lint

      - name: Run codestyle check
        run: pnpm format:check

      - name: Run e2e tests
        run: pnpm test:e2e
