name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Run lint
        run: pnpm lint

      - name: Run codestyle check
        run: pnpm format:check

      - name: Run e2e tests
        run: pnpm test:e2e
